
@endpoint=http://localhost:{{$dotenv PORT}}/api
@route=dates


#########################  FEATURE /PLACES  #####################

### récupération de toutes les dates
GET {{endpoint}}/{{route}}
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhVXNlciI6eyJpZCI6MiwibGFzdF9uYW1lIjoiR0FERVNTQVVEIiwiZmlyc3RfbmFtZSI6Ik5vw6ltaWUiLCJlbWFpbCI6Im5vZW1pZUBnbWFpbC5mciIsInBob25lIjoiMDcwNzA3MDcwNyIsImFkcmVzcyI6InJ1ZSBkdSBwYXJjIiwiemlwX2NvZGUiOiIzODUwMCIsImNpdHkiOiJDSElSRU5TIiwic3RhdHVzIjp0cnVlLCJyb2xlIjoiYWRtaW4iLCJhZ3JlZW1lbnQiOnRydWUsImNyZWF0ZWRfYXQiOiIyMDI0LTAyLTE1VDE1OjAxOjA0LjY1NFoiLCJ1cGRhdGVkX2F0IjpudWxsfSwiaWF0IjoxNzA4MDY4NjA1fQ.Vzw5jnJEsowR4zB8bxSeyBX6dsqrJYi16_9rJ6RN2rc


### creation d'une date
POST {{endpoint}}/{{route}}
Content-Type: application/json

{
  "date" : "2024-01-06T00:00:00.000Z"
}

### creation d'une date au mauvais format
POST {{endpoint}}/{{route}}
Content-Type: application/json

{
  "date" : "2024/06/06"
}

### creation d'une date avec une valeur manquante
POST {{endpoint}}/{{route}}
Content-Type: application/json

{
  "date" : "2024-06"
}

#########################  FEATURE DATES/:id  #####################

### récupération d'une date avec un id
GET {{endpoint}}/{{route}}/26

### récupération d'une date avec un id qui n'est pas un nombre
GET {{endpoint}}/{{route}}/n

### récupération d'une date avec un id qui n'existe pas
GET {{endpoint}}/{{route}}/200


### Modification d'une date par son id
PATCH {{endpoint}}/{{route}}/26
Content-Type: application/json

{
  "date" : "2024-04-10 00:00:00+00"
}

### Modification d'une date par un id incorrect
PATCH {{endpoint}}/{{route}}/bip
Content-Type: application/json

{
   "date" : "2024-2-14 00:00:00+00"
}

### Modification d'une date avec un id inexistant
PATCH {{endpoint}}/{{route}}/200
Content-Type: application/json

{
    "date" : "2024-02-14 00:00:00+00"
}

### Modification d'une date avec la propriété manquante
PATCH {{endpoint}}/{{route}}/2
Content-Type: application/json

{

}

### Modification d'une date avec la propriété avec le mauvais type
PATCH {{endpoint}}/{{route}}/2
Content-Type: application/json

{
  "date" : false
}


